version: '3'

services:
  todoback:
    # image: todobackend
    build: ./todo-app/back-end
    restart: always
    ports:
      - 3001:3001
    networks:
      - todo-app
  todofront:
    depends_on:
      - todoback
    # image: todofrontend
    build: ./todo-app/front-end
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
    ports:
      - 3000:3000
    networks:
      - todo-app
  todotests:
    depends_on:
      - todoback
      - todofront
    # image: todotests
    build: ./todo-app/tests
    restart: always
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - todo-app

networks:
  todo-app: